the alaskan growing season is all the sweeter because of how very short it is. alaskan-grown fruits and vegetables are listed below. you can also look up produce by seasons (spring:
  - summer, fall, winter). as any alaskan will know, this is a general guide: specifics for your area will vary depending on the year and on whether you're in juneau or nome, anchorage or fairbanks!
check out alaska local foods for more. then tell us what is your favorite thing about eating locally in alaska.:
  - check out alaska local foods for more. then tell us what is your favorite thing about eating locally in alaska.
 apples:
  - late august and early september
 beans:
  - late july through early september
 beets:
  - august and september (available cold storage from local sources into spring)
 blueberries:
  - late july into september
 broccoli:
  - june through september (available cold storage from local sources into winter)
 brussels sprouts:
  - late august through september (available cold storage from local sources into winter)
 cabbage:
  - late july through september (available cold storage from local sources into december)
 carrots:
  - august and september (available cold storage from local sources into april)
 cauliflower:
  - july into september (available cold storage from local sources into winter)
celeriac/celery root:
  - august and september
 celery:
  - august and september
cucumbers:
  - june through september
currants:
  - late july through early september
 gooseberries:
  - late august through early september
 greens:
  - late june through early september
green onions/scallions:
  - late june through september
 lettuce:
  - late june through september
 lingonberries:
  - august into september
 onions:
  - august and september (available cold storage from local sources year-round)
peas:
  - late july through early september
 potatoes:
  - late july through september (available cold storage from local sources year-round)
 radishes:
  - july through september
 raspberries:
  - late july into august
 rhubarb:
  - august through october
 rutabagas:
  - august and early september (available cold storage from local sources into winter)
spinach:
  - june into september
 strawberries:
  - july into september
 summer squash:
  - july into september
 tomatoes:
  - june through early september
 turnips:
  - august and september (available cold storage from local sources into spring)
winter squash:
  - september and october (available cold storage from local sources through winter
 zucchini:
  - july into september
