apples:
  - late august and early september
beans:
  - late july through early september
beets:
 - august and september
blueberries:
  - late july into september
broccoli:
  - june through september
brussels sprouts:
  - late august through september
cabbage:
  - late july through september
carrots:
  - august and september
cauliflower:
  - july into september
celeriac / celery root:
  - august and september
celery:
  - august and september
cucumbers:
  - june through september
currants:
  - late july through early september
gooseberries:
  - late august through early september
greens:
  - late june through early september
green onions / scallions:
  - late june through september
lettuce:
  - late june through september
lingonberries:
  - august into september
onions:
  - august and september
peas:
  - late july through early september
potatoes:
  - late july through september
radishes:
  - july through september
raspberries:
  - late july into august
rhubarb:
  - august through october
rutabagas:
  - august and early september
spinach:
  - june into september
strawberries:
  - july into september
summer squash:
  - july into september
tomatoes:
  - june through early september
turnips:
  - august and september
winter squash:
  - september and october
zucchini:
  - july into september
