apples:
  - late june through early october
asparagus:
  - march through june
basil:
  - may through october
beets:
  - april through july
blackberrries:
  - late june through early september
blueberries:
  - late may through early august
broccoli:
  - late may through early august
cabbage:
  - late april through early july
cantaloupes:
  - june through september
carrots:
  - year-round
cauliflower:
  - march through june
chard:
  - october through june
chicories:
  - fall and winter
chiles:
  - june through october
clementines:
  - december
collard greens:
  - october through june
corn:
  - late may through august
cucumbers:
  - late may through early november
eggplant:
  - late may through early october
fava beans:
  - february through may
fennel:
  - october through april
figs:
  - late july through early october
garlic:
  - june
grapes:
  - late july through early october
green beans:
  - late may through early november
green onions / scallions:
  - january through june
kale:
  - october through june
leeks:
  - april through august
lettuce:
  - march through early july
mandarins:
  - november and december
melons:
  - late june through september
mint:
  - year-round
morels:
  - spring
mushrooms (cultivated):
  - year-round
mushrooms (wild):
  - spring through fall
nectarines:
  - late may through early september
nettles:
  - march and april
new potatoes:
  - may
okra:
  - june through october
onions:
  - late april through early november
oranges:
  - november through january
oregano:
  - year-round
parsley:
  - year-round
parsnips:
  - november through march
peaches:
  - late may through early september
pears:
  - august through november
pea greens:
  - march through may
peanuts:
  - may through august
peas and pea pods:
  - late april through early july
pecans:
  - year-round
peppers (sweet):
  - june through october
persimmons:
  - late september through december
plums & pluots:
  - july and august
potatoes:
  - late may through august
pumpkins:
  - late september through early november
radishes:
  - march through june
radishes (daikon):
  - october through march
raspberries:
  - june and july
rhubarb:
  - february through may
rosemary:
  - year-round
rutabagas:
  - late september through early december
sage:
  - year-round
shallots:
  - june and july
shelling beans:
  - july through november
snap peas, snow peas, pea pods:
  - late april through early july
sorrel:
  - year-round
spinach:
  - late march through early july
squash (summer):
  - late april through september
squash (winter):
  - late august through december
strawberries:
  - late march through early july
sweet potatoes:
  - july through november
tangerines:
  - december
thyme:
  - year-round
tomatoes:
  - june through october
turnips:
  - january through april
watermelons:
  - june through september
winter squash:
  - late august through december
zucchini:
  - late april through september
zucchini blossoms:
  - late april through september
