apples:
  - late june through early october (cold storage until spring)
asparagus:
  - march through june
basil:
  - may through october
beets:
  - april through july (year-round from storage)
blackberrries:
  - late june through early september
blueberries:
  - june through early august
broccoli:
  - late may through early august
cabbage:
  - late april through early july
cantaloupes:
  - june through september
carrots:
  - year-round
cauliflower:
  - march through june
chard:
  - march through may and september through november
chicories:
  - fall and winter
collard greens:
  - march through may and september through november
corn:
  - late may through august
cucumbers:
  - late may through october
eggplant:
  - july through early october
fava beans:
  - february through may
fennel:
  - october through april
garlic:
  - harvested in june (cured and stored year-round)
grapes:
  - late july through early october
green beans:
  - late may through early november
green onions/scallions:
  - january through june
kale:
  - march through may and september through november
leeks:
  - april through august
lettuce:
  - march through early july
melons:
  - late june through september
mint:
  - year-round
morels:
  - spring
mushrooms (cultivated):
  - year-round
mushrooms (wild):
  - spring through fall
nectarines:
  - june through early september
nettles:
  - march and april
new potatoes:
  - may
okra:
  - june through october
onions:
  - late april through early november (stored year-round)
oregano:
  - april through october
parsley:
  - april through october
parsnips:
  - november through march
peaches:
  - late may through early september
pears:
  - august through november
pea greens:
  - march through may
peanuts:
  - may through august
peas and pea pods:
  - late april through early july
pecans:
  - year-round
peppers (sweet):
  - june through october
plums & pluots:
  - july and august
potatoes:
  - late may through august (available from storage year-round)
pumpkins:
  - late september through early november
radishes:
  - march through june
radishes (daikon:
  - watermelon, other large varieties), october through march
raspberries:
  - june and july
rhubarb:
  - february through may
rosemary:
  - april through october
rutabagas:
  - late september through early december
sage:
  - april through october
shallots:
  - june and july (from storage all year)
shelling beans:
  - july through november
snap peas/snow peas/pea pods:
  - , late april through early july
sorrel:
  - april through october
spinach:
  - march through may and september through november
squash (summer):
  - late april through september
squash (winter):
  - late august through december
strawberries:
  - late march through early july
sweet potatoes:
  - harvested july through november but available from storage year-round
thyme:
  - april through october
tomatoes:
  - june through october
turnips:
  - january through april
watermelons:
  - july through october
winter squash:
  - late august through december
zucchini:
  - late april through september
zucchini blossoms:
  - late april through september
