apples:
  - july through september
apricots:
  - may through june
arugula:
  - september through may
asparagus:
  - march and april
basil:
  - august through november
beets:
  - november through may
black-eyed peas:
  - july through september
blackberrries:
  - may and early june
blueberries:
  - june and early july
bok choy:
  - october through march
broccoli:
  - october through march
broccoli raab:
  - december through march
brussels sprouts:
  - december through march
cabbage:
  - january through april
carrots:
  - october through may
celeriac / celery root:
  - january through april
celery:
  - january through april
chiles:
  - july through september
clementines:
  - december through march
corn:
  - june through october
cucumbers:
  - april through september
dates:
  - october and november
figs:
  - june through october
garlic:
  - february through july
grapefruit:
  - december through march
grapes:
  - july and august
green beans:
  - june through october
green onion / scallions:
  - october through march
greens:
  - december through may
herbs:
  - year-round
key limes:
  - october and november
kohlrabi:
  - december through march
leeks:
  - december through july
lemons:
  - december through april
lettuce:
  - october through may
melons:
  - june through august
nectarines:
  - may through july
okra:
  - july through september
onions:
  - april through july
oranges:
  - december through march
parsnips:
  - december through march
peaches:
  - may through august
pears:
  - mid-august through september
peas:
  - april through june
plums & pluots:
  - june through august
potatoes:
  - april through october
pumpkins:
  - august through november
radishes:
  - october through may
radishes:
  - july through october
rutabagas:
  - december through march
shelling beans:
  - july through september
spinach:
  - october through may
squash (summer):
  - april through september
squash (winter):
  - august through november
strawberries:
  - february through april
sweet onions:
  - april through june
sweet peppers:
  - july through october
sweet potatoes:
  - december through march
tangerines:
  - december through march
tomatoes:
  - may through november
turnips:
  - october through march
zucchini:
  - april through september
zucchini blossoms:
  - march through september
