apples:
  - late summer through fall (cold storage until spring)
apricots:
  - late spring through early summer
artichokes:
  - spring and again early fall
arugula:
  - available year-round but best in spring and fall
asparagus:
  - spring
avocados:
  - classically summer, but now harvested year-round
basil:
  - summer
beets:
  - year-round
belgian endive:
  - available year-round but best in fall and winter
blackberrries:
  - summer
blueberries:
  - summer
boysenberries:
  - early summer
broccoli:
  - year-round but best in fall and winter
broccoli raab:
  - fall through spring
brussels sprouts:
  - late fall and winter
cabbage:
  - best in late fall and winter but available year-round
cantaloupes:
  - late summer
cardoons:
  - winter and early spring
carrots:
  - year-round
cauliflower:
  - best in fall and winter but available year-round
celeriac/celery root:
  - fall and winter
celery:
  - best in fall and winter but available year-round
chard:
  - summer and fall
cherries:
  - late spring and summer
chickpeas (a.k.a. garbanzo beans):
  - fresh in summer (dried year-round)
chicories:
  - fall and winter
chiles:
  - summer
clementines:
  - winter
collard greens:
  - year-round
corn:
  - summer
cucumbers:
  - summer
edamame:
  - fall
eggplant:
  - summer and early fall
escarole:
  - fall and winter
fava beans:
  - spring
fennel:
  - fall through spring
fiddleheads:
  - spring
figs:
  - summer and fall
garlic:
  - summer and fall (stored year-round)
gooseberries:
  - summer
garlic scapes/green garlic:
  - spring
grapefruit:
  - winter and spring
grapes:
  - late summer and early fall
green beans:
  - summer and early fall
green onions:
  - spring through fall
horseradish:
  - fall and winter
huckleberries:
  - late summer and early fall
jerusalem artichokes/sunchokes:
  - fall and winter
kale:
  - best in fall and winter
kiwis:
  - winter and into spring
kohlrabi:
  - late fall through spring
kumquats:
  - late winter and spring
leeks:
  - fall through spring
lemongrass:
  - summer and fall
lemons:
  - winter and spring
lettuce:
  - available year-round nationally but best in spring
limes:
  - late summer and fall
mandarins:
  - winter
mangos:
  - summer
marionberries:
  - summer
melons:
  - summer and early fall
mint:
  - year-round
morels:
  - spring
mushrooms (cultivated):
  - year-round
mushrooms (wild):
  - spring through fall
nectarines:
  - summer
nettles:
  - spring
new potatoes:
  - spring
okra:
  - late summer and early fall
onions:
  - spring through fall (stored in winter)
oranges (navel):
  - winter and spring
oranges (valencia):
  - spring and summer
oregano:
  - year-round
parsley:
  - year-round
parsnips:
  - fall through spring
peaches:
  - summer
pears:
  - fall
pea greens:
  - spring
peas and pea pods:
  - spring and early summer
peppers (sweet):
  - summer and early fall
persimmons:
  - fall and early winter
plums & pluots:
  - summer
pomegranates:
  - fall
pommelos:
  - winter
potatoes:
  - late summer through fall but available from storage year-round
pumpkins:
  - fall
quinces:
  - fall
radicchio:
  - late summer through early spring
radishes:
  - spring through fall
radishes (daikon:
  - watermelon, other large varieties), fall and winter
rapini:
  - fall through spring
raspberries:
  - summer
rhubarb:
  - spring and early summer
rosemary:
  - year-round
rutabagas:
  - fall and winter
sage:
  - year-round
salsify:
  - fall and winter
scallions:
  - spring through fall
shallots:
  - summer and fall (from storage through winter)
shelling beans:
  - summer and early fall
snap peas/snow peas/pea pods:
  - spring
sorrel:
  - year-round
spinach:
  - year-round
spring onions:
  - spring
squash (summer):
  - summer
squash (winter):
  - fall and winter
stinging nettles:
  - spring
strawberries:
  - spring and summer
sunchokes/jerusalem artichokes:
  - fall and winter
sweet onions:
  - spring and summer
sweet potatoes:
  - fall and winter
tangerines:
  - winter
thyme:
  - year-round
tomatillos:
  - late summer
tomatoes:
  - summer
turnips:
  - fall through spring
watercress:
  - year-round
watermelons:
  - summer
winter squash:
  - fall and winter
zucchini:
  - summer
zucchini blossoms:
  - summer
