apples:
  - july through october (cold storage until spring)
arugula:
  - may through september
asparagus:
  - may and june
basil:
  - july through september
beets:
  - june through december
blackberries:
  - late july through mid-august
blueberries:
  - july and august
broccoli:
  - june through november
broccoli raab:
  - august through november
brussels sprouts:
  - september through november
cabbage:
  - june through october
cantaloupes:
  - august and september
carrots:
  - june through september (local harvest available from storage through march)
cauliflower:
  - august through november
celeriac/celery root:
  - september through november
celery:
  - august through october
chard:
  - may through november
cherries:
  - july
chicories:
  - september and october
corn:
  - june through august
cranberries:
  - october through december
cucumbers:
  - july through october
currants:
  - august
eggplant:
  - july through october
escarole:
  - september and october
fava beans:
  - may and june
fennel:
  - october and november
fiddleheads:
  - april and may
garlic:
  - july through october (stored year-round)
garlic scapes/green garlic:
  - may and june
grapes:
  - september and october
green beans:
  - july through september
green onions/scallions:
  - may through september
kale:
  - june through november
herbs:
  - april through september
kohlrabi:
  - june and july:
  - september and october
leeks:
  - august through december
lettuce:
  - may through october
melons:
  - july through october
mint:
  - spring and summer
morels:
  - spring
mushrooms (cultivated):
  - year-round
mushrooms (wild):
  - spring through fall
nectarines:
  - august and september
nettles:
  - spring
new potatoes:
  - may
okra:
  - august and september
onions:
  - july through october (stored in winter)
oregano:
  - june through october
parsley:
  - may through november
parsnips:
  - april and may and again  october through december
peaches:
  - july through september
pears:
  - august through december
pea greens:
  - april through june
peas and pea pods:
  - june and july
peppers (sweet):
  - july through october
plums & pluots:
  - august and september
potatoes:
  - july through december (available from storage year-round)
pumpkins:
  - september through november
radicchio:
  - september and october
radishes:
  - may through september
raspberries:
  - july though september
rhubarb:
  - may through july
rutabagas:
  - august through november
shelling beans:
  - september through november
snap peas/snow peas/pea pods:
  - june through september
spinach:
  - may through september
squash (summer):
  - july through september
squash (winter):
  - august through december
strawberries:
  - june
thyme:
  - may through september
tomatoes:
  - july through september
turnips:
  - august through november (local harvest available from storage through the winter)
watermelons:
  - august through october
winter squash:
  - august through december
zucchini:
  - july through september
zucchini blossoms:
  - june and july
