avocados:
  - june through january
bananas:
  - august through october
basil:
  - march through november
blueberries:
  - april through june
broccoli:
  - october through may
broccoli raab:
  - october through may
brussels sprouts:
  - novemeber through march
cabbage:
  - november through june
cantaloupes:
  - march through july
carrots:
  - november through june
cauliflower:
  - november through may
celeriac/celery root:
  - november through june
celery:
  - november through june
cilantro:
  - november through may
chard:
  - november through may
chiles:
  - august through june
coconuts:
  - harvested year-round
collard greens:
  - november through may
corn:
  - august through june
cucumbers:
  - october through june
eggplant:
  - september through june
dragon fruits:
  - june through november
fava beans:
  - march through june
fennel:
  - september through june
grapefruit:
  - september through june
grapes:
  - august and september
green beans:
  - harvested year-round
green onions/scallions:
  - harvested year-round
jackfruit:
  - may through november
kale:
  - november through may
guava:
  - harvested year-round
leeks:
  - harvested year-round
lemongrass:
  - september through may
lettuce:
  - november through may
limes:
  - harvested year-round
lychee:
  - july and august
mandarins:
  - october through june
mangoes:
  - may through september
melons:
  - march through july
mushrooms (cultivated):
  - year-round
okra:
  - august through january
onions:
  - harvested year-round
oranges (navel):
  - october through may
oranges (valencia):
  - january through august
oregano:
  - year-round
papaya:
  - harvested year-round
parsley:
  - year-round
passion fruits:
  - july through march
pea greens:
  - january through april
peanut:
  - may through december
peas and pea pods:
  - january through may
peppers (sweet):
  - october through july
pommelos:
  - december through april
potatoes:
  - january through july
pumpkins:
  - fall
quinces:
  - fall
radishes:
  - october through june
raspberries:
  - summer
scallions/green onions:
  - harvested year-round
shelling beans:
  - august through november
spinach:
  - february and march
squash (summer):
  - september through june
strawberries:
  - october through june
tangerines:
  - september through may
thyme:
  - year-round
tomatillos:
  - september through june
tomatoes:
  - september through june
watermelons:
  - april through july
zucchini:
  - september through june
