avocados:
  - september through april
bananas:
  - june through october
cabbage:
  - year-round
carrots:
  - year-round
celery:
  - april through august
corn:
  - year-round
cucumbers:
  - year-round
eggplant:
  - year-round
ginger:
  - february through november
green beans:
  - year-round
green onions / scallions:
  - year-round
hearts of palm:
  - year-round
herbs:
  - year-round
lettuce:
  - year-round
limes:
  - june through march
luau (taro leaf):
  - year-round
lychees:
  - may through september
mangoes:
  - march through november
melons:
  - may through september
mushrooms :
  - year-round
"ohi'a 'ai (mountain apples)":
  - june into october
onions:
  - year-round
oranges:
  - year-round
papayas:
  - year-round
pineapples:
  - year-round
radishes:
  - year-round
radishes (daikon and other large varieties):
  - year-round
rambutans:
  - october through march
spinach:
  - year-round
squash (summer):
  - june through march
squash (winter):
  - june through march
strawberries:
  - january through april
starfruit:
  - september through april
sweet onions:
  - june through december
sweet peppers:
  - year-round
sweet potatoes:
  - year-round
tangerines:
  - september through february
taro:
  - year-round
tomatoes:
  - year-round
zucchini:
  - year-round
zucchini blossoms:
  - year-round
