growing seasons and crop availability will vary year to year and by microclimates within the state. in the warmest areas:
  - seasons start earlier and last longer (some items like greens, carrots, beets, and radishes may be harvested year-round in the most temperate areas); in colder areas harvest times start later and end sooner.
you can also look up produce by seasons: spring:
  - summer, fall, winter.
apples:
  - august through november (cold storage until may)
apricots:
  - july through august
arugula:
  - may through september
asparagus:
  - april and may
basil:
  - june through september
beets:
  - june through october
blackberrries:
  - august and september
blueberries:
  - august and september
boysenberries:
  - july and august
broccoli:
  - august through november
cabbage:
  - august through november
cantaloupes:
  - august and september
carrots:
  - august through november
cauliflower:
  - september through november
celery:
  - august through october
cilantro:
  - july through october
chard:
  - july through october
cherries:
  - june and july
corn:
  - july through september
cucumbers:
  - july through september
eggplant:
  - august through october
fava beans:
  - may and june
fennel:
  - june through october
fiddleheads:
  - april and may
gooseberries:
  - july and august
grapes:
  - september and october
green beans:
  - july and august
green onions/scallions:
  - june through october
horseradish:
  - september through november
huckleberries:
  - july into september
kale:
  - august through october
leeks:
  - august through november
lettuce:
  - may and june
melons:
  - august and september
mint:
  - april through september
morels:
  - april and may
mushrooms (cultivated):
  - year-round
mushrooms (wild):
  - spring through fall
nectarines:
  - july through september
nettles:
  - april and may
new potatoes:
  - april and may
onions:
  - august through december (from storage into may)
oregano:
  - year-round
parsley:
  - year-round
parsnips:
  - september and october
peaches:
  - august through october
pears:
  - september through november
pea greens:
  - april through may
peas and pea pods:
  - june through septmeber
peppers (sweet):
  - august through october
plums & pluots:
  - august and september
potatoes:
  - available from storage year-round
pumpkins:
  - september through november
radishes:
  - june through august
raspberries:
  - june through september
rhubarb:
  - june through august
rutabagas:
  - september and october (available from storage through winter)
shallots:
  - august through october (from storage through winter)
shelling beans:
  - august and september
snap peas/snow peas/pea pods:
  - june through september
spinach:
  - may through july
squash (summer):
  - july through september
squash (winter):
  - august through december
strawberries:
  - june through august
tomatoes:
  - july through october
turnips:
  - september through november (available from storage through winter)
winter squash:
  - august through december
zucchini:
  - july through september
zucchini blossoms:
  - june through august
