apples:
  - august through november
apricots:
  - july through august
arugula:
  - may through september
asparagus:
  - april and may
basil:
  - june through september
beets:
  - june through october
blackberrries:
  - august and september
blueberries:
  - august and september
boysenberries:
  - july and august
broccoli:
  - august through november
cabbage:
  - august through november
cantaloupes:
  - august and september
carrots:
  - august through november
cauliflower:
  - september through november
celery:
  - august through october
cilantro:
  - july through october
chard:
  - july through october
cherries:
  - june and july
corn:
  - july through september
cucumbers:
  - july through september
eggplant:
  - august through october
fava beans:
  - may and june
fennel:
  - june through october
fiddleheads:
  - april and may
gooseberries:
  - july and august
grapes:
  - september and october
green beans:
  - july and august
green onions / scallions:
  - june through october
horseradish:
  - september through november
huckleberries:
  - july into september
kale:
  - august through october
leeks:
  - august through november
lettuce:
  - may and june
melons:
  - august and september
mint:
  - april through september
morels:
  - april and may
mushrooms (wild):
  - spring through fall
nectarines:
  - july through september
nettles:
  - april and may
new potatoes:
  - april and may
onions:
  - august through december
oregano:
  - year-round
parsley:
  - year-round
parsnips:
  - september and october
peaches:
  - august through october
pears:
  - september through november
pea greens:
  - april through may
peas and pea pods:
  - june through september
peppers (sweet):
  - august through october
plums & pluots:
  - august and september
pumpkins:
  - september through november
radishes:
  - june through august
raspberries:
  - june through september
rhubarb:
  - june through august
rutabagas:
  - september and october
shallots:
  - august through october
shelling beans:
  - august and september
snap peas, snow peas, pea pods:
  - june through september
spinach:
  - may through july
squash (summer):
  - july through september
squash (winter):
  - august through december
strawberries:
  - june through august
tomatoes:
  - july through october
turnips:
  - september through november
winter squash:
  - august through december
zucchini:
  - july through september
zucchini blossoms:
  - june through august
