apples:
  - july into november
apricots:
  - july and august
arugula:
  - spring
  - fall
asparagus:
  - may and june
basil:
  - june through september
beets:
  - july into october
blackberrries:
  - late july and august
blueberries:
  - july and august
boysenberries:
  - june and july
broccoli:
  - june through october
broccoli raab:
  - september and october
brussels sprouts:
  - september through november
cabbage:
  - july through november
cantaloupes:
  - july through september
carrots:
  - july through november
cauliflower:
  - june through november
celeriac / celery root:
  - august and september
celery:
  - august and september
cilantro:
  - june through september
chard:
  - june through october
cherries:
  - june and july
chicories:
  - august through november
collard greens:
  - june through october
corn:
  - august and september
cucumbers:
  - july through september
eggplant:
  - july through september
escarole:
  - september into november
gooseberries:
  - july and august
green beans:
  - august and september
green onions / scallions:
  - june through october
herbs:
  - june through october
kale:
  - june through october
leeks:
  - august through october
lettuce:
  - may through september
melons:
  - july through september
mint:
  - june through september
morels:
  - spring
mushrooms (wild):
  - spring through fall
nectarines:
  - july and august
nettles:
  - spring
okra:
  - september
onions:
  - june through november
oregano:
  - august through october
parsley:
  - june through october
parsnips:
  - october and november
pears:
  - august through october
pea greens:
  - spring
peas and pea pods:
  - july and august
peppers (sweet):
  - july through september
potatoes:
  - june into october
pumpkins:
  - september and october
radicchio:
  - august through october
radishes:
  - may through october
raspberries:
  - july into september
rhubarb:
  - june through august
rutabagas:
  - october and november
shallots:
  - june through october
shelling beans:
  - september
snap peas, snow peas, pea pods:
  - june through august
spinach:
  - june through october
squash (summer):
  - july through october
squash (winter):
  - august through october
strawberries:
  - july and august
sweet potatoes:
  - september
tomatoes:
  - july through september
turnips:
  - october and november
watermelons:
  - august and september
winter squash:
  - august through october
zucchini:
  - july through september
zucchini blossoms:
  - july and august
