apples:
  - august through october
arugula:
  - april through june
  - september through november
asparagus:
  - late may through june
basil:
  - july through september
beets:
  - july through october
blackberrries:
  - late august
blueberries:
  - late july through august
bok choy:
  - july into october
broccoli:
  - late june into october
brussels sprouts:
  - september into november
cabbage:
  - july into october
cantaloupes:
  - august and september
carrots:
  - june into november
cauliflower:
  - september into november
chard:
  - july into october
collard greens:
  - july through november
corn:
  - late july through september
cranberries:
  - october through december
cucumbers:
  - august and september
eggplant:
  - late july through september
fiddleheads:
  - april and may
garlic:
  - august through october
garlic scapes / green garlic:
  - may and june
grapes:
  - september and october
green beans:
  - august and september
green onions:
  - may through october
herbs:
  - spring through fall
kale:
  - july through november
leeks:
  - august through november
lettuce:
  - may through november
melons:
  - august and september
mint:
  - june through october
morels:
  - spring
mushrooms (wild):
  - spring through fall
nettles:
  - spring
onions:
  - august through october
parsnips:
  - october and november
pears:
  - august into october
pea greens:
  - may and june
peas and pea pods:
  - june into august
peppers (sweet):
  - august and september
plums:
  - early september
potatoes:
  - august through october
pumpkins:
  - october
radishes:
  - may into september
raspberries:
  - late july through early august
  - late september
rhubarb:
  - may and june
rutabagas:
  - october and november
shallots:
  - august and september
snap peas, snow peas, pea pods:
  - july and august
spinach:
  - june
  - late august into october
squash (summer):
  - july through september
squash (winter):
  - september into november
strawberries:
  - late june into july
tomatoes:
  - july into october
turnips:
  - september and october
watermelons:
  - august and september
winter squash:
  - september into november
zucchini:
  - july through september
zucchini blossoms:
  - june through september
