apples:
  - august through october
asparagus:
  - may through august
basil:
  - august and september
beets:
  - june through october
blueberries:
  - july into august
broccoli:
  - june through october
brussels sprouts:
  - august through mid-november
cabbage:
  - june through october
cantaloupes:
  - august and september
carrots:
  - june through october (local harvest available from storage through winter)
cauliflower:
  - august through november
celery:
  - august through october
chard:
  - july through september
corn:
  - mid-june through mid-august
cucumbers:
  - july through mid-october
eggplant:
  - july through mid-october
garlic:
  - august through november
grapes:
  - september
green beans:
  - july through september
green onions:
  - june through september
greens (various):
  - june through october
herbs:
  - july through october
leeks:
  - august through october
lettuce (various):
  - june through september
melons:
  - august and september
mint:
  - april through october
onions:
  - august through october (local harvest available from storage year-round)
parsnips:
  - april and may and again in october through november (local harvest available from storage through winter)
pea greens:
  - june and july
peas:
  - july through august
peppers (sweet):
  - july through september
potatoespotatoes:
  - july through october (local harvest available from storage year-round)
pumpkins:
  - october
radishesradishes:
  - may through october
raspberries:
  - june into august
rhubarb:
  - may through june
rutabagas:
  - october through november (available from storage into spring)
shelling beans:
  - september through october (local harvest available dried year-round)
spinach:
  - may through october
summer squash:
  - july through october
strawberries:
  - june and july
tomatoes:
  - july through early october
turnips:
  - august through november (local harvest available from storage through february
watermelons:
  - august through september
wild rice:
  - local harvest available from storage year-round
winter squash:
  - august through october (local harvest available from storage through february)
zucchini:
  - july through october
zucchini blossoms:
  - june through august
