apples:
  - july through october
arugula:
  - may through september
asparagus:
  - april through june
basil:
  - july through september
beets:
  - may through october
blackberrries:
  - july into august
blueberries:
  - july into august
broccoli:
  - june through october
brussels sprouts:
  - august through november
cabbage:
  - june through november
cantaloupes:
  - august and september
carrots:
  - may through november
cauliflower:
  - august through november
celeriac / celery root:
  - august through october
celery:
  - august through october
chard:
  - may through september
cherries:
  - june and july
cilantro:
  - june through september
corn:
  - mid-june through mid-august
cucumbers:
  - july through mid-october
eggplant:
  - july through mid-october
fava beans:
  - may
garlic:
  - august through november
garlic scapes / green garlic:
  - may and june
grapes:
  - august and september
green beans:
  - july through september
green onions / scallions:
  - june through september
greens (various):
  - may through november
herbs:
  - various, may through october
kale:
  - june through november
leeks:
  - august through october
lettuce (various):
  - may through october
melons:
  - july through september
morels:
  - spring
mushrooms (cultivated):
  - year-round
mushrooms (wild):
  - spring through fall
onions:
  - august through october
parsley:
  - may through september
parsnips:
  - april and may
  - october through november
peaches:
  - july and august
pears:
  - august through october
peas and pea pods:
  - june through august
peppers (sweet):
  - june through september
persimmons:
  - october
plums & pluots:
  - july and august
potatoes:
  - july through november
pumpkins:
  - september through october
radishes:
  - may through october
raspberries:
  - june into august
rhubarb:
  - april through june
shelling beans:
  - september through october
spinach:
  - may through october
squash (summer):
  - july through october
squash (winter):
  - august through november
strawberries:
  - june and july
tomatoes:
  - july through october
turnips:
  - august through november
watermelons:
  - august through september
zucchini:
  - july through october
zucchini blossoms:
  - july and august
