apples:
  - august through november
apricots:
  - june through august
arugula:
  - september through june
asparagus:
  - february through may
basil:
  - year-round
beets:
  - april through november
blackberrries:
  - june through september
black-eyed peas:
  - june through november
bok choy:
  - fall through spring
broccoli:
  - fall and winter
broccoli raab:
  - august through november
brussels sprouts:
  - september through november
cabbage:
  - june through september
cantaloupes:
  - july through november
carrots:
  - june through november
cauliflower:
  - september through november
celeriac / celery root:
  - september through november
celery:
  - august through november
cilantro:
  - year-round
chard:
  - september through june
cherries:
  - june and july
chicories:
  - september through november
chiles:
  - july through november
collard greens:
  - september through june
corn:
  - june through november
cucumbers:
  - june through november
eggplant:
  - june through november
escarole:
  - september through december
fennel:
  - august through december
figs:
  - june through september
garlic:
  - june through august
garlic scapes / green garlic:
  - march and april
grapes:
  - july through november
green beans:
  - june through november
green onions:
  - june through november
herbs:
  - year-round
kale:
  - september through june
kohlrabi:
  - july through november
leeks:
  - july through december
lettuce:
  - year-round
melons:
  - july through november
mint:
  - year-round
morels:
  - spring
mushrooms (wild):
  - spring
  - fall
nectarines:
  - june through september
new potatoes:
  - april through june
okra:
  - june through october
onions:
  - june through november
oregano:
  - year-round
parsley:
  - year-round
parsnips:
  - september through december
peaches:
  - june through september
pears:
  - september through november
pea greens:
  - february through april
peas and pea pods:
  - february through july
pecans:
  - september through november
peppers (sweet):
  - june through october
pistachios:
  - september through november
plums & pluots:
  - june through september
potatoes:
  - june through december
pumpkins:
  - september through november
radicchio:
  - september through november
radishes:
  - september through june
rapini:
  - september through june
raspberries:
  - june through september
rhubarb:
  - april and may
rosemary:
  - year-round
rutabagas:
  - september through december
sage:
  - year-round
scallions:
  - june through november
shallots:
  - june through november
shelling beans:
  - june through november
snap peas, snow peas, pea pods:
  - february through june
spinach:
  - february through july
squash (summer):
  - may through october
squash (winter):
  - september through december
sweet potatoes:
  - july through december
thyme:
  - year-round
tomatillos:
  - june through november
tomatoes:
  - june through november
turnips:
  - july through december
watermelons:
  - july through september
winter squash:
  - september through december
zucchini:
  - may through october
zucchini blossoms:
  - may through august
