apples:
  - august through november (may be available from storage into spring)
arugula:
  - april through june (may be available from hot houses in winter)
asparagus:
  - april through june
basil:
  - may through september
beans:
  - may through october
beets:
  - april through june
blueberries:
  - may through august
bok choy:
  - october through june
broccoli:
  - may through june and october through december
brussels sprouts:
  - november through february
cabbage:
  - october through may
cantaloupes:
  - june through august
carrots:
  - october through may
cauliflower:
  - october through december
celery:
  - october through february
chard:
  - october through may
collard greens:
  - october through june
corn:
  - june and july
cucumbers:
  - june through august
edamame:
  - june through september
eggplant:
  - june through october
figs:
  - july and august
garlic:
  - may through october (available from storage year-round)
green garlic:
  - march through may
grapes:
  - july through october
kale:
  - october through may
leeks:
  - october through may
lettuce:
  - september through june
melons:
  - june through september
mushrooms (cultivated):
  - year-round
okra:
  - may through october
onions:
  - march through november
parsnips:
  - october through december
peaches:
  - may through august
peas and pea pods:
  - february through may
pecans:
  - september through december
peppers:
  - june through september
persimmons:
  - september through november
plums & pluots:
  - may through july
potatoes:
  - may through august (available from storage through winter)
radishes:
  - march through june
spinach:
  - november through may
squash (summer):
  - may through october
squash (winter):
  - august through december
strawberries:
  - april through june
sweet onions:
  - may and june
sweet potatoes:
  - august through february
tomatoes:
  - june through october
turnips:
  - october through april
watermelons:
  - june through september
zucchini:
  - may through october
zucchini blossoms:
  - may through september
