apples:
  - august through february
arugula:
  - spring
  - fall
asparagus:
  - spring
basil:
  - may through november
beets:
  - year-round
blueberries:
  - may into july
broccoli:
  - may
  - october and november
broccoli raab:
  - october into december
brussels sprouts:
  - october through december
butter beans:
  - july and august
cabbage:
  - may through december
cantaloupes:
  - july and august
carrots:
  - year-round
cauliflower:
  - october through december
celeriac / celery root:
  - october through january
celery:
  - september through november
cilantro:
  - year-round
chard:
  - march into december
cherries:
  - late spring and summer
chicories:
  - october through december
chiles:
  - august and september
collard greens:
  - march into december
corn:
  - june through august
cucumbers:
  - june through november
eggplant:
  - june through august
escarole:
  - september through december
fennel:
  - fall through spring
garlic:
  - july and august
garlic scapes / green garlic:
  - march and april
grapes:
  - august into october
green beans:
  - june through september
greens:
  - march into december
green onions:
  - march through november
herbs:
  - various year-round
kale:
  - march into december
kohlrabi:
  - october through march
leeks:
  - year-round
lettuce:
  - year-round
melons:
  - june through august
mint:
  - year-round
morels:
  - spring
mushrooms (cultivated):
  - year-round
mushrooms (wild):
  - spring through fall
nectarines:
  - june through september
nettles:
  - march and april
new potatoes:
  - march and april
okra:
  - august
onions:
  - year-round
oregano:
  - year-round
parsley:
  - year-round
parsnips:
  - october into december
peaches:
  - june through september
pea greens:
  - march and april
peas and pea pods:
  - june through august
peppers (sweet):
  - june through august
potatoes:
  - july
pumpkins:
  - september and october
radicchio:
  - september through december
radishes:
  - march into november
sage:
  - year-round
scallions:
  - march through november
shallots:
  - summer and fall
shelling beans:
  - august and september
snap peas, snow peas, pea pods:
  - june and july
sorrel:
  - year-round
spinach:
  - year-round
squash (summer):
  - may through september
squash (winter):
  - fall and winter
strawberries:
  - april through june
sweet potatoes:
  - year-round
thyme:
  - year-round
tomatoes:
  - july into october
turnips:
  - september into march
watermelons:
  - june through august
winter squash:
  - september into january
zucchini:
  - may through september
zucchini blossoms:
  - may through july
