looking for more great texas local foods? see our guide to texas local foods.:
  - looking for more great texas local foods? see our guide to texas local foods.
apples:
  - july through november
beets:
  - november through february
blackberrries:
  - may through july
broccoli:
  - october through may
cabbage:
  - year-round
cantaloupes:
  - may through december
carrots:
  - year-round
celery:
  - year-round
cherries:
  - june and july
chickpeas (garbanzo beans):
  - june and july
chiles:
  - august and september
corn:
  - late may into august
cucumbers:
  - april through december
fava beans:
  - april through june
figs:
  - june and july, second crop in fall
grapefruit:
  - october through april
grapes:
  - august through october
greens:
  - year-round
honeydew:
  - may through january
mushrooms:
  - year-round
okra:
  - late summer and early fall
onions:
  - march through september
oranges:
  - october through june
peaches:
  - june through sept
peanuts:
  - september and october
pears:
  - august through november
peppers (sweet):
  - year-round
plums & pluots:
  - may (red and yellow) and july through september
pomegranates:
  - october through december
potatoes:
  - march through october
new potatoes:
  - may and june
spinach:
  - january through may
squash (summer):
  - june through sept
squash (winter):
  - october through april
sweet onions:
  - spring and summer
sweet potatoes:
  - year-round
tomatoes:
  - april through october
turnips:
  - year-round
watermelons:
  - may through november
