apples:
  - august through october
apricots:
  - mid-august through mid-september
asparagus:
  - may
basil:
  - june through september
beets:
  - july through october
blackberrries:
  - august and september
blueberries:
  - june and july
broccoli:
  - july through october
broccoli raab:
  - september and october
cabbage:
  - august into november
cantaloupes:
  - mid-august through mid-october
carrots:
  - august through november
cauliflower:
  - august through october
celeriac / celery root:
  - september and october
celery:
  - mid-july into october
chard:
  - july through october
cherries:
  - june
chicories:
  - september through november
chiles:
  - august into october
collard greens:
  - august through october
corn:
  - mid-july into october
cucumbers:
  - mid-july into october
eggplant:
  - mid-august into october
escarole:
  - september into november
fava beans:
  - may
fennel:
  - june through september
garlic:
  - july through september
green garlic:
  - may and june
grapes:
  - september into october
green beans:
  - mid-july through september
green onions / scallions:
  - june through october
herbs:
  - july through october
kale:
  - august into november
leeks:
  - august through march
lettuce:
  - june into november
melons:
  - mid-august into october
mint:
  - may through october
morels:
  - april through june
]mushrooms (wild):
  - spring through fall
nettles:
  - april through june
new potatoes:
  - june and july
onions:
  - august through march
oregano:
  - august and september
parsley:
  - june through october
parsnips:
  - september through november
peaches:
  - august and september
pears:
  - september and october
pea greens:
  - spring
peas and pea pods:
  - spring and early summer
peppers (sweet):
  - august into october
plums & pluots:
  - august
potatoes:
  - july through november
pumpkins:
  - september and october
radicchio:
  - august through november
radishes:
  - may through november
raspberries:
  - august into october
rhubarb:
  - may through september
rutabagas:
  - october and november
scallions / green onions:
  - may through october
shallots:
  - july through october
shelling beans:
  - september
snap peas, snow peas, pea pods:
  - may through july
spinach:
  - may through october
sprouts:
  - year-round
squash (summer):
  - august into october
squash (winter):
  - august into december
strawberries:
  - june into october
sweet onions:
  - august through october
tomatoes:
  - july into october
turnips:
  - october into december
watermelons:
  - september into october
winter squash:
  - september into november
zucchini:
  - august into october
zucchini blossoms:
  - august
