apples:
  - august through october (available from cold storage until spring)
arugula:
  - april through june and september through november
asparagus:
  - late may through june
basil:
  - july through september
beets:
  - july through october (available from cold storage through spring)
blackberrries:
  - late august
blueberries:
  - late july through august
bok choy:
  - july into october
broccoli:
  - end of june into october
brussels sprouts:
  - september into november
cabbage:
  - july into october (available from cold storage into spring)
cantaloupes:
  - august and september
carrots:
  - june into november (available from cold storage all year)
cauliflower:
  - september into november
chard:
  - july into october
collard greens:
  - july through november
corn:
  - end of july through september
cranberries:
  - october through december
cucumbers:
  - august and september
eggplant:
  - end of july through september
fiddleheads:
  - april and may
garlic:
  - august through october (stored year-round)
garlic scapes/green garlic:
  - may and june
grapes:
  - september and october
green beans:
  - august and september
green onions:
  - may through october
herbs:
  - various spring through fall
kale:
  - july through november
leeks:
  - august through november
lettuce:
  - may through november
melons:
  - august and september
mint:
  - june through october
morels:
  - spring
mushrooms (cultivated):
  - year-round
mushrooms (wild):
  - spring through fall
nettles:
  - spring
new potatoes:
  - june
onions:
  - august through october (available from cold storage into spring)
parsnips:
  - october and november (available from cold storage through spring)
pears:
  - august into october
pea greens:
  - may and june
peas and pea pods:
  - june into august
peppers (sweet):
  - august and september
plums:
  - early september
potatoes:
  - august through october (available from cold storage all year)
pumpkins:
  - october (available from cold storage into winter)
radishes:
  - may into september
raspberries:
  - late july through early august, second crop at the end of september
rhubarb:
  - may and june
rutabagas:
  - october and november (available from cold storage into spring)
shallots:
  - august and september (from cold storage through winter)
snap peas/snow peas/pea pods:
  - july and august
spinach:
  - june, second crop start send of august into october
squash (summer):
  - july through september
squash (winter):
  - september into november (available from cold storage through spring)
strawberries:
  - end of june into july
tomatoes:
  - july into october
turnips:
  - september and october (available from cold storage through spring)
watermelons:
  - august and september
winter squash:
  - september into november (available from cold storage through spring)
zucchini:
  - july through september
zucchini blossoms:
  - june through september
