apples:
  - august through november
apricots:
  - june and july
artichokes:
  - september and october
arugula:
  - may through december
asparagus:
  - april through june
basil:
  - june through november
beets:
  - june through january
blackberrries:
  - july through september
blueberries:
  - june through september
boysenberries:
  - june through august
broccoli:
  - june through september
brussels sprouts:
  - september through january
cabbage:
  - june through february
cantaloupes:
  - august through october
carrots:
  - june through january
cauliflower:
  - july through september
celeriac / celery root:
  - august through november
celery:
  - august through november
chard:
  - may through february
cherries:
  - june and july
chiles:
  - august through october
collard greens:
  - may through february
corn:
  - august through october
cucumber:
  - july through october
edible flowers:
  - april through september
eggplant:
  - august through november
fava beans:
  - april through june
fennel:
  - year-round
fiddleheads:
  - april and may
figs:
  - july and august
garlic:
  - august through november
garlic scapes / green garlic:
  - spring
grapes:
  - august through october
green beans:
  - july through september
green onions / scallions:
  - spring through fall
greens:
  - may through february
herbs:
  - various year-round
huckleberries:
  - august and september
jerusalem artichokes / sunchokes:
  - july through october
kale:
  - may through february
kiwi:
  - september through november
kohlrabi:
  - august through october
leeks:
  - september through march
lettuce:
  - may through november
marionberries:
  - july
melons:
  - august through october
mint:
  - may through december
morels:
  - may
mushrooms (cultivated):
  - year-round
mushrooms (wild):
  - spring through fall
nectarines:
  - summer
nettles:
  - march through may
new potatoesnew potatoes:
  - spring
onions:
  - june through october
oregano:
  - may through december
parsley:
  - may through december
parsnips:
  - september through february
pears:
  - august and november
pea greens:
  - may
peas and pea pods:
  - june and july
peppers (sweet):
  - august through october
persimmons:
  - fall
plums and pluots:
  - august and september
potatoes:
  - year-round
pumpkins:
  - october through november
quinces:
  - october
radicchio:
  - may through november
radishes:
  - may through november
radishes (daikon):
  - june through november
raspberries:
  - june through august
rhubarb:
  - april through june
rosemary:
  - may through december
rutabaga:
  - september through february
sage:
  - may through december
salsify:
  - september through december
scallions / green onions:
  - may through november
shallots:
  - september through december
shelling beans:
  - september and october
snap peas, snow peas, pea pods:
  - june and july
sorrel:
  - may through november
spinach:
  - may through december
sprouts:
  - may through october
squash (summer) :
  - june through october
squash (winter) :
  - september through february
stinging nettles:
  - april and may
strawberries:
  - june and july
sunchokes / jerusalem artichokes:
  - july through october
thyme:
  - may through december
tomatoes:
  - july through october
turnips:
  - june through january
watercress:
  - may through december
watermelon:
  - august and september
zucchini:
  - june through october
zucchini blossoms:
  - june through october
